language: node_js
branches:
  only:
  - master
  - /^release\/.*$/
cache: npm
stages:
  - check
  - test
  - cov

node_js:
  - '16'

os:
  - linux
  - osx
  - windows

script: npm run test:node -- --bail
after_success: npx codecov

jobs:
  include:
    - stage: check
      script:
        - npx aegir dep-check
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npx aegir test -t browser -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npx aegir test -t browser -t webworker -- --browsers FirefoxHeadless

notifications:
  email: false
